### ISSUE TITLE
关于仿真中无人机检测的一些疑问

### ISSUE THREAD

**Issue by XXLiu-HNU** [ZJU-FAST-Lab/Active-Relative-Localization#3]
感谢开源！在阅读仿真代码的时候有一些疑惑，还请不吝赐教！

**疑问1** 
在阅读仿真代码的时候发现，在无人机检测部分是不是进行了简化？我看在[ego_replan_fsm.cpp](https://github.com/ZJU-FAST-Lab/Active-Relative-Localization/blob/main/src/planner/plan_manage/src/ego_replan_fsm.cpp)文件中，当触发观察之后，目标无人机的位置貌似是真实值加上一个噪声。是不是因为在进行仿真的时候，无法真正通过观测来获得其他无人机的位姿，所以采取了折中的方法。[drone_detect](https://github.com/ZJU-FAST-Lab/Active-Relative-Localization/tree/main/src/planner/drone_detect) 文件并没有起到作用

**疑问2**
 在进行实物实验的时候，论文里说采用的是YOLOv8， 检测出来的无人机的位姿的误差一般有多大呀，感觉这个误差对于整个系统的影响还是挺大的，另外检测的实时性如何，有没有具体项目可以参考呀~

最后还是非常感谢把这么优秀的项目进行开源！

**Comment by AshadowZ** [comment]
感谢您对该工作的兴趣！

1.  是的，对于检测部分做了简化。我在ego_replan_fsm.cpp写了fake yolo的定时器回调函数，当无人机发现其他无人机持续在自己fov内一段时间后，就认为触发了观测，把真实相对位置加上噪声发布出去。因为这个仿真环境是ego planner的，比较轻量，渲染不了目标识别所需的图像。drone_detect是ego planner的遗留代码。

2.  实机实验时，相对测量是通过yolo在当前图像中获取其他无人机的bounding box，然后从realsense的深度图中提取对应的深度得到的。yolo给的bounding box位置是非常准的，深度误差如果realsense标定得比较好的话，在常规场景大概5m之内误差都6-7cm左右。yolo推理所需的时间没测过，我选的最小的模型，实验看上去work了之后就没管了，不过我尝试中等或更大的yolov8模型时，nx会过热关机。

**Comment by XXLiu-HNU** [comment]
感谢回复！
